firefox: WIP fix darwin build
The build succeeds now, however the resulting binary is only partially
functional.

    dyld: warning, DYLD_ setting caused circular dependency in /src/nixpkgs/firefox-71.0/obj-x86_64-apple-darwin18.7.0/dist/Firefox.app/Contents/MacOS/libnss3.dylib
    dyld: Symbol not found: _SECKEY_RSAPublicKeyTemplate
      Referenced from: /nix/store/hf4x2iz00g0h1pyaywzmdprd7wy62alp-nss-3.47.1/lib/libssl3.dylib
      Expected in: /src/nixpkgs/firefox-71.0/obj-x86_64-apple-darwin18.7.0/dist/Firefox.app/Contents/MacOS/libnss3.dylib
     in /nix/store/hf4x2iz00g0h1pyaywzmdprd7wy62alp-nss-3.47.1/lib/libssl3.dylib
    [Parent 94527, IPC Launch #1] WARNING: parent WaitForMessage() failed: 0x10004003 (ipc/rcv) timed out: file /src/nixpkgs/firefox-71.0/ipc/glue/GeckoChildProcessHost.cpp, line 1199
    [Parent 94527, Gecko_IOThread] WARNING: Failed to launch tab subprocess: file /src/nixpkgs/firefox-71.0/ipc/glue/GeckoChildProcessHost.cpp, line 672